/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Entity.ConModel;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author USER
 */
public class Consulta extends javax.swing.JFrame {
    ConModel conexionDBMS;
    /**
     * Creates new form Notificaion
     */
    public Consulta() {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            conexionDBMS.getConnection();
            Statement s;
            ResultSet rs;
            s=conexionDBMS.getConnection().createStatement();
            rs=s.executeQuery("serect * from receta order by valor_d");
            while(rs.next())
            {
                list1.add(""+rs.getInt("id_r"));
                list2.add(rs.getString("nombre"));
                list3.add(""+rs.getInt("valor_d"));
            }
            conexionDBMS.getConnection().close();
           }
        catch(Exception e)
           {}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        list2 = new java.awt.List();
        list3 = new java.awt.List();
        volver = new javax.swing.JButton();
        notificaion = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, 270));
        getContentPane().add(list2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 260, 270));
        getContentPane().add(list3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, 270));

        volver.setText("Volver al menu");
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        notificaion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        notificaion.setForeground(new java.awt.Color(0, 0, 0));
        notificaion.setText("Tuplas existentes");
        getContentPane().add(notificaion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 200, 50));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Diseño\\thumbnail-white.jpg")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private java.awt.List list1;
    private java.awt.List list2;
    private java.awt.List list3;
    private javax.swing.JLabel notificaion;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
