/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
import Entity.ConModel;


public class Menu extends javax.swing.JFrame {
 ConModel con;
    public Menu() {
        con = new ConModel();
        con.getConnection();
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        dropelements = new javax.swing.JButton();
        viewelements = new javax.swing.JButton();
        newelement = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        dropelements.setText("     Elimitar receta     ");
        getContentPane().add(dropelements, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        viewelements.setText("       Ver recetas        ");
        viewelements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewelementsActionPerformed(evt);
            }
        });
        getContentPane().add(viewelements, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        newelement.setText("Añadir nueva receta");
        newelement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newelementActionPerformed(evt);
            }
        });
        getContentPane().add(newelement, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Manejo y registro de recetas");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Diseño\\thumbnail-white.jpg")); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newelementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newelementActionPerformed
        NuevoEl nuevo=new NuevoEl(con);
        nuevo.setVisible(true);
        dispose();
    }//GEN-LAST:event_newelementActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void viewelementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewelementsActionPerformed
       Consulta nuevo=new Consulta();
        nuevo.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewelementsActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton dropelements;
    private javax.swing.JButton newelement;
    private javax.swing.JButton salir;
    private javax.swing.JButton viewelements;
    // End of variables declaration//GEN-END:variables
}
