/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Entity.ConModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class NuevoEl extends javax.swing.JFrame {

    public ConModel conexionDBMS;
   
    
    public NuevoEl(ConModel con) {
        conexionDBMS=con;
        initComponents();
    }

    private NuevoEl() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tV = new javax.swing.JTextField();
        tID = new javax.swing.JTextField();
        tNOM = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregar.setText("Añadir");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("valor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        getContentPane().add(tV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 310, -1));
        getContentPane().add(tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 310, -1));
        getContentPane().add(tNOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 310, -1));

        Titulo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Nueva Receta");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Diseño\\thumbnail-white.jpg")); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
      
        conexionDBMS.getConnection();
        boolean flag=false;
        if(!tNOM.getText().isEmpty())
          {  try{
              PreparedStatement ps = conexionDBMS.getConnection().prepareStatement("select 1 from Receta where nombre=?");
              ps.setString(1,tNOM.getText());
              ResultSet rs= ps.executeQuery();
              flag=rs.next();
                 }
          catch(Exception e){}
           if(!flag) 
            {
             try{
                PreparedStatement p=conexionDBMS.getConnection().prepareStatement("insert into Receta values(?,?,?)");
                p.setInt(1,Integer.parseInt(tID.getText()));
                p.setString(2,tNOM.getText());
                p.setInt(3,Integer.parseInt(tV.getText()));
                p.executeUpdate();
                JOptionPane.showMessageDialog(null,"receta ingresada");
                conexionDBMS.getConnection().close();
                tID.setText("");
                tNOM.setText("");
                tV.setText("");
                
             }
             catch(Exception e)
                   {}
            
            }
           else
            {JOptionPane.showMessageDialog(null,"datos erroneos,costo negativos o nombre repetido");
             tV.setText("");
              tNOM.setText("");
               tID.setText("");
            }
          }
        else
          {
          JOptionPane.showMessageDialog(null,"datos erroneos,nombre repetido");
          tV.setText("");
              tNOM.setText("");
               tID.setText("");
          }
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoEl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoEl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoEl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoEl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoEl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tNOM;
    private javax.swing.JTextField tV;
    // End of variables declaration//GEN-END:variables
}
